### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ghost** [schana/dayz-mod-autorun#4]

**Comment by schana** [comment]
What isn't working?

**Comment by DogDaysA** [comment]
schana, I just tried to compile it for a test box (nothing official yet, I wanted to contact you) but I am not getting it to work either.  I do not see it when I try to customize the keybinding (it just doesn't show up).  I joined the Carim discord in hopes of contacting you there.

**Comment by schana** [comment]
This sounds more like a packaging issue. If you're using the DayZ tools packager, you need to make sure it includes everything, like the inputs XML. Also, ensure the directory names match the config.cpp so it can find everything.

**Comment by DogDaysA** [comment]
And completely closed.  Not sure why I had to have you post that.  This works perfectly once you pay attention to it!!  Thank you for all of the work that went into this!
